# This rule is not used by the project kafka-topic-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the kafka.fluffyfoxtail.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kafka-topic-operator
    app.kubernetes.io/managed-by: kustomize
  name: kafkatopic-editor-role
rules:
- apiGroups:
  - kafka.fluffyfoxtail.com
  resources:
  - kafkatopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka.fluffyfoxtail.com
  resources:
  - kafkatopics/status
  verbs:
  - get
