# This patch bind operator controller name to service account
- op: replace
  path: /subjects/0/name
  value: "kafka-topic-operator-controller-manager"
- op: replace
  path: /subjects/0/namespace
  value: "kafka-topic-operator-system"