---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kafka.fluffyfoxtail.com
  resources:
  - kafkatopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka.fluffyfoxtail.com
  resources:
  - kafkatopics/finalizers
  verbs:
  - update
- apiGroups:
  - kafka.fluffyfoxtail.com
  resources:
  - kafkatopics/status
  verbs:
  - get
  - patch
  - update
